[versions]

#/**
#* Compile sdk version
#* 按照指定sdk版本进行编译  不影响实际运行  尽量写最新的，最好跟targetsdkversion版本保持一致
#*/

compileSdk = "34"

#/**
#* Min sdk version
#* App支持的最低版本 Android 6.0
#*/
minSdk = "23"

#AGP的版本
agp = "8.13.1"

# AndroidX相关的稳定版本，组件依赖时使用
androidxAppcompatStable = "1.6.1"
activityStable = "1.7.2"
androidxActivityKtxStable = "1.7.2"
androidxConstraintlayoutStable = "2.1.4"
kotlinStable = "1.7.21"


#较新版本，App依赖时使用
androidxAppcompat = "1.7.1"
androidxConstraintlayout = "2.2.1"
androidxCore = "1.17.0"
androidxRecyclerview = "1.4.0"
material = "1.13.0"
cardview = "1.0.0"

#kotlin
kotlin = "2.2.21"

#三方库
vanniktechPublish = "0.35.0"
moshiKotlin = "1.15.2"
flexboxLayout = "3.0.0"

#我的开源库
xeonBuildManager = "0.0.7"
xeonApplication = "1.0.9"
xeonCoroutine = "1.0.5"
xeonBinding = "1.0.2"


[libraries]

# 稳定版本
androidx-appcompat-stable = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompatStable" }
androidx-activity-stable = { group = "androidx.activity", name = "activity", version.ref = "activityStable" }
androidx-activity-ktx-stable = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivityKtxStable" }
androidx-constraintlayout-stable = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintlayoutStable" }
kotlin-bom-stable = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlinStable" }


#androidX
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidxRecyclerview" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }


#三方库
moshiKotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshiKotlin" }
flexbox-layout = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexboxLayout" }

#我自己的开源库
xeonyu-application = { group = "com.xeonyu", name = "application", version.ref = "xeonApplication" }
xeonyu-coroutine = { group = "com.xeonyu", name = "coroutine", version.ref = "xeonCoroutine" }
xeonyu-binding = { group = "com.xeonyu", name = "binding", version.ref = "xeonBinding" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
#版本发布三方插件
vanniktechPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechPublish" }
#自定义的插件
xeonyu-application = { id = "com.xeonyu.plugin.application", version.ref = "xeonBuildManager" }
xeonyu-library = { id = "com.xeonyu.plugin.library", version.ref = "xeonBuildManager" }